using System.IO;
using System.Text;
using System.Windows;
using System.Windows.Media;
using ThinkMeta.Music.Notation.Fonts.Smufl.Metadata.Generated;

namespace ThinkMeta.Music.Notation.Fonts.Smufl.Svg.SmuflSvgCodeGenerator;

internal class WpfSmuflSvgCodeGenerator(string[] args) : SmuflSvgCodeGeneratorBase(args)
{
    public override async Task GenerateAsync()
    {
        var stringBuilder = new StringBuilder();

        _ = stringBuilder
            .AppendLine("// generated by ThinkMeta.Music.Notation.Fonts.Smufl.Svg.SmuflSvgCodeGenerator")
            .AppendLine("using System.Windows;")
            .AppendLine("using System.Windows.Media;")
            .AppendLine()
            .AppendLine($"namespace {Args["namespace"]};")
            .AppendLine();

        _ = stringBuilder
            .AppendLine("file static class StreamGeometryContextExtensions")
            .AppendLine("{")
            .Append(Indent1)
            .AppendLine("public static StreamGeometryContext BeginFigure(this StreamGeometryContext context, (double x, double y) p)")
            .Append(Indent1)
            .AppendLine("{")
            .Append(Indent2)
            .AppendLine("context.BeginFigure(new Point(p.x, p.y), true, true);")
            .Append(Indent2)
            .AppendLine("return context;")
            .Append(Indent1)
            .AppendLine("}")
            .AppendLine()
            .Append(Indent1)
            .AppendLine("public static StreamGeometryContext BezierTo(this StreamGeometryContext context, (double x, double y) p1, (double x, double y) p2, (double x, double y) p3)")
            .Append(Indent1)
            .AppendLine("{")
            .Append(Indent2)
            .AppendLine("context.BezierTo(new Point(p1.x, p1.y), new Point(p2.x, p2.y), new Point(p3.x, p3.y), true, true);")
            .Append(Indent2)
            .AppendLine("return context;")
            .Append(Indent1)
            .AppendLine("}")
            .AppendLine()
            .Append(Indent1)
            .AppendLine("public static StreamGeometryContext LineTo(this StreamGeometryContext context, (double x, double y) p)")
            .Append(Indent1)
            .AppendLine("{")
            .Append(Indent2)
            .AppendLine("context.LineTo(new Point(p.x, p.y), true, true);")
            .Append(Indent2)
            .AppendLine("return context;")
            .Append(Indent1)
            .AppendLine("}")
            .AppendLine()
            .Append(Indent1)
            .AppendLine("public static StreamGeometryContext PolyBezierTo(this StreamGeometryContext context, params (double x, double y)[] p)")
            .Append(Indent1)
            .AppendLine("{")
            .Append(Indent2)
            .AppendLine("context.PolyBezierTo([.. p.Select(p => new Point(p.x, p.y))], true, true);")
            .Append(Indent2)
            .AppendLine("return context;")
            .Append(Indent1)
            .AppendLine("}")
            .AppendLine()
            .Append(Indent1)
            .AppendLine("public static StreamGeometryContext PolyLineTo(this StreamGeometryContext context, params (double x, double y)[] p)")
            .Append(Indent1)
            .AppendLine("{")
            .Append(Indent2)
            .AppendLine("context.PolyLineTo([.. p.Select(p => new Point(p.x, p.y))], true, true);")
            .Append(Indent2)
            .AppendLine("return context;")
            .Append(Indent1)
            .AppendLine("}")
            .AppendLine("}")
            .AppendLine();

        _ = stringBuilder
            .AppendLine($"public static class {Args["class"]}")
            .AppendLine("{");

        var glyphs = Font!.Glyphs.Where(g => g.Unicode?.Length == 1 && g.PathData is not null && GlyphNameMappings.GlyphName2CodePointMap.Values.Contains(g.Unicode[0]));

        foreach (var glyph in glyphs) {
            var codePoint = (int)glyph.Unicode[0];
            var glyphName = GlyphNameMappings.GlyphName2CodePointMap.Single(kv => kv.Value == codePoint).Key;
            _ = stringBuilder
                .Append(Indent1)
                .AppendLine("/// <summary>")
                .Append(Indent1)
                .AppendLine($"/// {GlyphNameMappings.GlyphName2DescriptionMap[glyphName]}.")
                .Append(Indent1)
                .AppendLine("/// </summary>")
                .Append(Indent1)
                .AppendLine($"public static Geometry {glyphName} {{ get; }} = Create{glyphName}Geometry();");
        }

        foreach (var glyph in glyphs) {
            var codePoint = (int)glyph.Unicode[0];
            var glyphName = GlyphNameMappings.GlyphName2CodePointMap.Single(kv => kv.Value == codePoint).Key;
            _ = stringBuilder
                .AppendLine()
                .Append(Indent1)
                .AppendLine($"private static Geometry Create{glyphName}Geometry()")
                .Append(Indent1)
                .AppendLine("{")
                .Append(Indent2)
                .AppendLine($"var geometry = new StreamGeometry();")
                .Append(Indent2)
                .AppendLine("using (var context = geometry.Open()) {")
                .Append(Indent3)
                .Append("_ = context");

            var pathFigureCollection = PathFigureCollection.Parse(glyph.PathData);

            foreach (var pathFigure in pathFigureCollection) {
                _ = stringBuilder
                    .AppendLine()
                    .Append(Indent4)
                    .Append($".BeginFigure({Point2String(pathFigure.StartPoint)})");

                foreach (var segment in pathFigure.Segments) {
                    _ = segment switch {
                        BezierSegment bezier => stringBuilder
                                                    .AppendLine()
                                                    .Append(Indent4)
                                                    .Append($".BezierTo({Point2String(bezier.Point1)}, {Point2String(bezier.Point2)}, {Point2String(bezier.Point3)})"),
                        LineSegment line => stringBuilder
                                                    .AppendLine()
                                                    .Append(Indent4)
                                                    .Append($".LineTo({Point2String(line.Point)})"),
                        PolyBezierSegment polyBezier => stringBuilder
                                                    .AppendLine()
                                                    .Append(Indent4)
                                                    .Append($".PolyBezierTo({string.Join(", ", polyBezier.Points.Select(Point2String))})"),
                        PolyLineSegment polyLine => stringBuilder
                                                    .AppendLine()
                                                    .Append(Indent4)
                                                    .Append($".PolyLineTo({string.Join(", ", polyLine.Points.Select(Point2String))})"),
                        _ => throw new NotSupportedException($"Segment type '{segment.GetType()}' is not supported."),
                    };
                }
            }

            _ = stringBuilder
                .AppendLine(";")
                .Append(Indent2)
                .AppendLine("}")
                .AppendLine()
                .Append(Indent2)
                .AppendLine("geometry.Freeze();")
                .Append(Indent2)
                .AppendLine("return geometry;")
                .Append(Indent1)
                .AppendLine("}");
        }

        _ = stringBuilder
            .AppendLine("}");

        await File.WriteAllTextAsync(Args["out"], stringBuilder.ToString());
    }

    private static string Point2String(Point p) => $"({p.X}, {-p.Y})";
}